# Generated by Django 3.1.6 on 2021-02-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_privat', models.CharField(max_length=45)),
                ('user', models.CharField(max_length=45)),
                ('ip_public', models.CharField(max_length=45)),
                ('loguri', models.TextField()),
            ],
        ),
    ]
